// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Ywf0sX9RpDdtpKseYhbx8MrwgK7ChyA',
    appId: '1:677228271448:web:4d5917f8657e2aa567f72d',
    messagingSenderId: '677228271448',
    projectId: 'bossam-e675e',
    authDomain: 'bossam-e675e.firebaseapp.com',
    storageBucket: 'bossam-e675e.firebasestorage.app',
    measurementId: 'G-TPDG0B954Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV5uq5Gp1iIXObAjk6ErA5i9fij7rIrlQ',
    appId: '1:677228271448:android:15c1e84e5f89224d67f72d',
    messagingSenderId: '677228271448',
    projectId: 'bossam-e675e',
    storageBucket: 'bossam-e675e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi_qxJaVqsGkuoFXbU-5mLnUk3XRjbEvY',
    appId: '1:677228271448:ios:901b7196e1036e7367f72d',
    messagingSenderId: '677228271448',
    projectId: 'bossam-e675e',
    storageBucket: 'bossam-e675e.firebasestorage.app',
    iosClientId: '677228271448-1um661179mkvtl020sg6gmod22tdtc4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.bossam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi_qxJaVqsGkuoFXbU-5mLnUk3XRjbEvY',
    appId: '1:677228271448:ios:901b7196e1036e7367f72d',
    messagingSenderId: '677228271448',
    projectId: 'bossam-e675e',
    storageBucket: 'bossam-e675e.firebasestorage.app',
    iosClientId: '677228271448-1um661179mkvtl020sg6gmod22tdtc4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.bossam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2Ywf0sX9RpDdtpKseYhbx8MrwgK7ChyA',
    appId: '1:677228271448:web:8936ec86c5453e8067f72d',
    messagingSenderId: '677228271448',
    projectId: 'bossam-e675e',
    authDomain: 'bossam-e675e.firebaseapp.com',
    storageBucket: 'bossam-e675e.firebasestorage.app',
    measurementId: 'G-S6Q87C59NF',
  );

}